/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package magazyn;

import javax.swing.JFrame;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author darvark
 */
public class Konfiguracja extends javax.swing.JFrame {

    /**
     * Creates new form Konfiguracja
     */
    public Konfiguracja() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        url_db = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        db_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        db_login = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        zapisz_konf_baz = new javax.swing.JButton();
        db_pass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        conf_output = new javax.swing.JTextArea();
        conf_close = new javax.swing.JButton();
        read_konf = new javax.swing.JButton();

        jLabel1.setText("URL");

        jLabel2.setText("Baza danych");

        jLabel3.setText("Login");

        jLabel4.setText("Hasło");

        zapisz_konf_baz.setText("Zapisz");
        zapisz_konf_baz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zapisz_konf_bazActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Prestige Elite Std", 0, 18)); // NOI18N
        jLabel5.setText("Konfiguracja bazy danych:");

        conf_output.setColumns(20);
        conf_output.setRows(5);
        jScrollPane1.setViewportView(conf_output);

        conf_close.setText("Zamknij");
        conf_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conf_closeActionPerformed(evt);
            }
        });

        read_konf.setText("Wczytaj");
        read_konf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read_konfActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(db_pass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 189, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(url_db, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                .add(jLabel1)
                                .add(jLabel2)
                                .add(db_name)
                                .add(db_login)))
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(0, 0, Short.MAX_VALUE)
                                .add(conf_close)
                                .add(36, 36, 36)
                                .add(zapisz_konf_baz)
                                .add(34, 34, 34)
                                .add(read_konf))
                            .add(layout.createSequentialGroup()
                                .add(jLabel3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 279, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(49, 49, 49))))
            .add(layout.createSequentialGroup()
                .add(181, 181, 181)
                .add(jLabel5)
                .add(0, 162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(15, 15, 15)
                .add(jLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1)
                .add(18, 18, 18)
                .add(url_db, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel2)
                        .add(18, 18, 18)
                        .add(db_name, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel3)
                        .add(18, 18, 18)
                        .add(db_login, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel4)
                        .add(18, 18, 18)
                        .add(db_pass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 188, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(zapisz_konf_baz)
                    .add(conf_close)
                    .add(read_konf))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zapisz_konf_bazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zapisz_konf_bazActionPerformed

        DataBase.url = url_db.getText();
        DataBase.baza = db_name.getText();
        DataBase.login = db_login.getText();
        char[] pass = db_pass.getPassword();//obejscie probelmy konfliktu typow. getPassword
        //zwraca tablice znakow, haslo jest typu string
        DataBase.password = new String(pass);
        String parametry = "URL: " + url_db.getText() + '\n' + "Nazwa bazy: " + db_name.getText() + '\n' + "Login: " + db_login.getText() + '\n' + "Haslo: " + DataBase.password;
        conf_output.setText("Wprowadzono następujące ustawienia bazy danych:\n" + parametry);
        IO konf = new IO();
        try {
            konf.zapis("db.cf");
        } catch (IOException e) {
        };
    }//GEN-LAST:event_zapisz_konf_bazActionPerformed

    private void conf_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conf_closeActionPerformed
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_conf_closeActionPerformed

    private void read_konfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read_konfActionPerformed
        // wczytuje konfiguracje z pliku
        File_Parser plik = new File_Parser();
        try {
            plik.parse();
            String parametry = "URL: " + DataBase.url + '\n' + "Nazwa bazy: " + DataBase.baza + '\n' + "Login: " + DataBase.login + '\n' + "Hasło: " + DataBase.password;
            conf_output.setText("Wprowadzono następujące ustawienia bazy danych:\n" + parametry);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Konfiguracja.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_read_konfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Konfiguracja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Konfiguracja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Konfiguracja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Konfiguracja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Konfiguracja().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conf_close;
    private javax.swing.JTextArea conf_output;
    private javax.swing.JTextField db_login;
    private javax.swing.JTextField db_name;
    private javax.swing.JPasswordField db_pass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton read_konf;
    private javax.swing.JTextField url_db;
    private javax.swing.JButton zapisz_konf_baz;
    // End of variables declaration//GEN-END:variables
}
