package magazyn;

import java.awt.event.ActionEvent;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import oracle.toplink.essentials.internal.sessions.DirectCollectionChangeRecord;

/**
 *
 * @author Marcin 'darvark' Iwaniuk
 */
public class Mag extends javax.swing.JFrame {

    /**
     * Creates new form Mag
     */
    public Mag() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        art_dodaj = new javax.swing.JButton();
        art_szukaj = new javax.swing.JButton();
        art_nazwa = new javax.swing.JTextField();
        art_jm = new javax.swing.JTextField();
        art_ilosc = new javax.swing.JTextField();
        art_ean = new javax.swing.JTextField();
        art_polka = new javax.swing.JTextField();
        art_regal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        art_output = new javax.swing.JTextPane();
        jLabel25 = new javax.swing.JLabel();
        art_ean1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        art_ilosc1 = new javax.swing.JTextField();
        dodaj_sztuk = new javax.swing.JButton();
        usun_sztuk1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        nazwa_add = new javax.swing.JTextField();
        nip_add = new javax.swing.JTextField();
        regon_add = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kontrachent_dodaj = new javax.swing.JButton();
        Szukaj = new javax.swing.JButton();
        miasto_add = new javax.swing.JTextField();
        ulica_add = new javax.swing.JTextField();
        kod_add = new javax.swing.JTextField();
        dom_add = new javax.swing.JTextField();
        lokal_add = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        output_kontrachent = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        zamowienie_dla = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        zamowienie_item = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        zamowienie_ilosc = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        zamowienie_data = new javax.swing.JTextField();
        zamowienie_add = new javax.swing.JButton();
        zamowienie_szukaj = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        zamowienie_output = new javax.swing.JTextPane();
        zamowienie_nr_dok = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pz_od = new javax.swing.JTextField();
        pz_ilosc = new javax.swing.JTextField();
        pz_item = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pz_output = new javax.swing.JTextPane();
        pz_dodaj = new javax.swing.JButton();
        pz_num = new javax.swing.JTextField();
        pz_szukaj_button = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        nr_dok_pz = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        wz_dokogo = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        wz_item = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        wz_ile = new javax.swing.JTextField();
        wz_add_button = new javax.swing.JButton();
        szukaj_wz = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        wz_find = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        wz_output = new javax.swing.JTextPane();
        jLabel24 = new javax.swing.JLabel();
        nr_dok_wz = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        show_info = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        sprawdz_pol = new javax.swing.JMenu();
        check_pol = new javax.swing.JMenuItem();
        create_baze = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${name}"), this, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${resizable}"), this, org.jdesktop.beansbinding.BeanProperty.create("resizable"));
        bindingGroup.addBinding(binding);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        art_dodaj.setText("Dodaj");
        art_dodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                art_dodajActionPerformed(evt);
            }
        });

        art_szukaj.setText("Szukaj");
        art_szukaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                art_szukajActionPerformed(evt);
            }
        });

        jLabel1.setText("Nazwa");

        jLabel2.setText("Jednostka");

        jLabel7.setText("Ilość");

        jLabel8.setText("EAN");

        jLabel9.setText("Półka");

        jLabel10.setText("Regał");

        jScrollPane8.setViewportView(art_output);

        jLabel25.setText("EAN");

        jLabel28.setText("Ilość");

        dodaj_sztuk.setText("Dodaj sztuki");
        dodaj_sztuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodaj_sztukActionPerformed(evt);
            }
        });

        usun_sztuk1.setText("Usun sztuki");
        usun_sztuk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usun_sztuk1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jPanel2Layout.createSequentialGroup()
                            .add(art_dodaj)
                            .add(168, 168, 168)
                            .add(art_szukaj))
                        .add(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(art_nazwa)
                                .add(art_jm)
                                .add(art_ilosc)
                                .add(art_ean)
                                .add(art_polka)
                                .add(art_regal))
                            .add(80, 80, 80)))
                    .add(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel10)
                            .add(jLabel9)
                            .add(jLabel8)
                            .add(jLabel7)
                            .add(jLabel2))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(0, 55, Short.MAX_VALUE)
                        .add(jScrollPane8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 383, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(59, 59, 59))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(art_ilosc1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                .add(art_ean1))
                            .add(jLabel25)
                            .add(jLabel28))
                        .add(42, 42, 42)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(dodaj_sztuk)
                            .add(usun_sztuk1))
                        .add(92, 92, 92))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(art_nazwa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(art_jm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(art_ilosc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel8)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(77, 77, 77)
                        .add(jScrollPane8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 199, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(28, 28, 28)))
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(art_ean, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel9)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(art_polka, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel10)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(art_regal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(art_dodaj)
                            .add(art_szukaj)))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel28)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(art_ilosc1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(dodaj_sztuk))
                        .add(18, 18, 18)
                        .add(jLabel25)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(art_ean1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(usun_sztuk1))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Artykuł", jPanel2);

        nazwa_add.setActionCommand("<Not Set>");

        nip_add.setColumns(10);

        jLabel3.setText("Nazwa kontrachenta");

        jLabel4.setText("Adres");

        jLabel5.setText("NIP");

        jLabel6.setText("Regon");

        kontrachent_dodaj.setText("Dodaj");
        kontrachent_dodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kontrachent_dodajActionPerformed(evt);
            }
        });

        Szukaj.setText("Szukaj");
        Szukaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SzukajActionPerformed(evt);
            }
        });

        jLabel11.setText("Kod");

        jLabel12.setText("Nr dom");

        jLabel13.setText("Nr lok");

        jLabel14.setText("Miasto");

        jLabel15.setText("Ulica");

        jScrollPane3.setViewportView(output_kontrachent);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(jPanel1Layout.createSequentialGroup()
                                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 176, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(kontrachent_dodaj))
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 97, Short.MAX_VALUE)
                                    .add(Szukaj))
                                .add(nip_add))
                            .add(regon_add, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 358, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(nazwa_add, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 356, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(ulica_add, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 275, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jLabel15))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(miasto_add, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 225, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(jLabel14))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(kod_add, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 83, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(dom_add, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(jLabel11)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(jLabel12)
                                        .add(32, 32, 32)))
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(lokal_add, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(9, 9, 9)
                                        .add(jLabel13))))
                            .add(jLabel5)
                            .add(jLabel6))
                        .add(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 360, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(jScrollPane3)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(nazwa_add, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(miasto_add, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel14))
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(ulica_add, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel15))
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel11)
                            .add(jLabel12)
                            .add(jLabel13))
                        .add(3, 3, 3)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(kod_add, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(dom_add, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lokal_add, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(24, 24, 24)
                        .add(jLabel5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(nip_add, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(30, 30, 30)
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(regon_add, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(45, 45, 45)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(kontrachent_dodaj)
                    .add(Szukaj))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Kontrachent", jPanel1);

        jLabel22.setText("Dla kogo");

        jLabel23.setText("Przedmiot");

        jLabel26.setText("Ilość");

        jLabel27.setText("Data");

        zamowienie_add.setText("Dodaj");
        zamowienie_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamowienie_addActionPerformed(evt);
            }
        });

        zamowienie_szukaj.setText("Szukaj");
        zamowienie_szukaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamowienie_szukajActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportView(zamowienie_output);

        jLabel17.setText("Numer dokumentu");

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel26)
                            .add(zamowienie_item, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 177, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(zamowienie_data, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 177, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel27)
                            .add(jLabel23)
                            .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, zamowienie_nr_dok)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, zamowienie_ilosc, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                            .add(jLabel17)
                            .add(zamowienie_dla, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 177, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 93, Short.MAX_VALUE)
                        .add(jScrollPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 429, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(132, 132, 132))
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel5Layout.createSequentialGroup()
                                .add(zamowienie_add)
                                .add(108, 108, 108)
                                .add(zamowienie_szukaj))
                            .add(jLabel22))
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createSequentialGroup()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(54, 54, 54)
                        .add(jLabel22)
                        .add(18, 18, 18)
                        .add(zamowienie_dla, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 18, Short.MAX_VALUE)
                        .add(jLabel23)
                        .add(18, 18, 18)
                        .add(zamowienie_item, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel27)
                        .add(18, 18, 18)
                        .add(zamowienie_data, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel26)
                        .add(18, 18, 18)
                        .add(zamowienie_ilosc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(23, 23, 23)
                        .add(jLabel17)
                        .add(18, 18, 18)
                        .add(zamowienie_nr_dok, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jScrollPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 338, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(41, 41, 41)))
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(zamowienie_add)
                    .add(zamowienie_szukaj))
                .add(45, 45, 45))
        );

        jTabbedPane1.addTab("Zamówienie", jPanel5);

        jLabel16.setText("Od kogo");

        jLabel18.setText("Przedmiot");

        jLabel19.setText("Ilość");

        jScrollPane1.setViewportView(pz_output);

        pz_dodaj.setText("Dodaj");
        pz_dodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pz_dodajActionPerformed(evt);
            }
        });

        pz_szukaj_button.setText("Szukaj");
        pz_szukaj_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pz_szukaj_buttonActionPerformed(evt);
            }
        });

        jLabel21.setText("Szukaj PZ");

        jLabel20.setText("Numer dokumentu");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(pz_item, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                        .add(jLabel18)
                        .add(jLabel19)
                        .add(pz_ilosc)
                        .add(pz_dodaj)
                        .add(jLabel21)
                        .add(pz_num, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 194, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(pz_od, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                        .add(jLabel16)
                        .add(nr_dok_pz))
                    .add(jLabel20))
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(7, 7, 7)
                        .add(pz_szukaj_button)
                        .addContainerGap(510, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 85, Short.MAX_VALUE)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 372, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(145, 145, 145))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(96, 96, 96)
                .add(jLabel16)
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(pz_od, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel18)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(pz_item, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel19)
                        .add(18, 18, 18)
                        .add(pz_ilosc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 21, Short.MAX_VALUE)
                        .add(jLabel20)
                        .add(18, 18, 18)
                        .add(nr_dok_pz, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(pz_dodaj)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel21))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 324, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 10, Short.MAX_VALUE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(pz_num, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pz_szukaj_button))
                .add(27, 27, 27))
        );

        jTabbedPane1.addTab("PZ", jPanel3);

        jLabel29.setText("Do kogo");

        jLabel30.setText("Przedmiot");

        jLabel31.setText("Ilość");

        wz_add_button.setText("Dodaj");
        wz_add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wz_add_buttonActionPerformed(evt);
            }
        });

        jLabel32.setText("Szukaj WZ");

        wz_find.setText("Szukaj");
        wz_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wz_findActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(wz_output);

        jLabel24.setText("Numer dokumentu");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(szukaj_wz, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 214, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(40, 40, 40)
                                .add(wz_find))
                            .add(jLabel32))
                        .addContainerGap())
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel30)
                            .add(jLabel31)
                            .add(wz_add_button)
                            .add(jLabel24)
                            .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel29)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, wz_dokogo)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, wz_item)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, wz_ile, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, nr_dok_wz)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 108, Short.MAX_VALUE)
                        .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 368, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(131, 131, 131))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(77, 77, 77)
                .add(jLabel29)
                .add(18, 18, 18)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(wz_dokogo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel30)
                        .add(18, 18, 18)
                        .add(wz_item, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel31)
                        .add(18, 18, 18)
                        .add(wz_ile, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel24)
                        .add(18, 18, 18)
                        .add(nr_dok_wz, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 16, Short.MAX_VALUE)
                        .add(wz_add_button)
                        .add(18, 18, 18)
                        .add(jLabel32))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 330, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE)))
                .add(18, 18, 18)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(szukaj_wz, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(wz_find))
                .add(27, 27, 27))
        );

        jTabbedPane1.addTab("WZ", jPanel4);

        show_info.setText("Plik");

        jMenuItem1.setText("O programie");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        show_info.add(jMenuItem1);

        jMenuItem8.setText("Exit");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        show_info.add(jMenuItem8);

        jMenuBar1.add(show_info);

        sprawdz_pol.setText("Narzędzia");

        check_pol.setText("Sprawdz połączenie");
        check_pol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_polActionPerformed(evt);
            }
        });
        sprawdz_pol.add(check_pol);

        create_baze.setText("Utwórz bazę");
        create_baze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_bazeActionPerformed(evt);
            }
        });
        sprawdz_pol.add(create_baze);

        jMenuItem3.setText("Konfiguracja");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        sprawdz_pol.add(jMenuItem3);

        jMenuBar1.add(sprawdz_pol);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jTabbedPane1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Kontrachent");

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        System.exit(0);        // domysle zachowanie na EXIT
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // opcja menu:edit -> konfiguracja
        Konfiguracja frame = new Konfiguracja();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void check_polActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_polActionPerformed
        // menu->edit->sprawdz polaczenie
        Polaczenie conn = new Polaczenie();
        conn.setVisible(true);
    }//GEN-LAST:event_check_polActionPerformed

    private void pz_szukaj_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pz_szukaj_buttonActionPerformed
        /**
         * szukaj dokumentu PZ
         */
        PZ pz = new PZ();
        String od_kogo = pz_od.getText();
        int dok = Integer.parseInt(pz_num.getText());
        pz_output.setText(pz.szukaj_pz(dok));
    }//GEN-LAST:event_pz_szukaj_buttonActionPerformed

    private void pz_dodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pz_dodajActionPerformed
        /**
         * dodaj dokument PZ
         */
        PZ pz = new PZ();
        int od_kogo = Integer.parseInt(pz_od.getText());
        int przedmiot = Integer.parseInt(pz_item.getText());
        int ilosc = Integer.parseInt(pz_ilosc.getText());
        int nr_dokumentu = Integer.parseInt(nr_dok_pz.getText());
        String pz_dok = "Nazwa: " + od_kogo + '\n' + "Przedmiot: " + przedmiot + '\n' + "Ilość: " + ilosc + '\n' + "Nr dokumentu: " + nr_dokumentu;
        //pz_output.setText("Dodano: \n");
        //pz_output.setText(pz_dok);
        pz_output.setText(pz.dodaj_pz(od_kogo, przedmiot, ilosc, nr_dokumentu));
    }//GEN-LAST:event_pz_dodajActionPerformed

    private void wz_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wz_findActionPerformed
        /**
         * szukaj dokumentu WZ
         */
        WZ wz = new WZ();
        int nr_dokumentu = Integer.parseInt(szukaj_wz.getText());
        wz_output.setText(wz.szukaj_wz_nr(nr_dokumentu));
    }//GEN-LAST:event_wz_findActionPerformed

    private void wz_add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wz_add_buttonActionPerformed
        /**
         * dodanie wz
         */
        WZ wz = new WZ();
        int do_kogo = Integer.parseInt(wz_dokogo.getText());
        int przedmiot = Integer.parseInt(wz_item.getText());
        int ilosc = Integer.parseInt(wz_ile.getText());
        int nr_dokumentu = Integer.parseInt(nr_dok_wz.getText());
        wz_output.setText(wz.dodaj_wz(do_kogo, przedmiot, ilosc, nr_dokumentu));
    }//GEN-LAST:event_wz_add_buttonActionPerformed

    private void zamowienie_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamowienie_addActionPerformed
        /**
         * dodanie zamowienia
         */
        Zamowienie zamow = new Zamowienie();
        String data = zamowienie_data.getText();
        int nip = Integer.parseInt(zamowienie_dla.getText());
        int ean = Integer.parseInt(zamowienie_item.getText());
        int amount = Integer.parseInt(zamowienie_ilosc.getText());
        int nr_dok = Integer.parseInt(zamowienie_nr_dok.getText());
        zamow.dodaj_zamowienie(nip, ean, data, nr_dok, amount);
        String uqery = "ID klienta: " + nip + "\nEAN: " + ean + "\nLiczba sztuk: " + amount + "\nNumer dokumentu zamówienia: " + nr_dok;
        zamowienie_output.setText("Dodano zamówienie\n" + uqery);
    }//GEN-LAST:event_zamowienie_addActionPerformed

    private void SzukajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SzukajActionPerformed
        /**
         * klawisz szukaj w panelu kontrachneta
         *
         */
        Kontrachent szukaj_kontrachenta = new Kontrachent();
        if (nazwa_add.getText().length() != 0) {
            output_kontrachent.setText(szukaj_kontrachenta.get_kontrachent(nazwa_add.getText()));
        } else if (Integer.parseInt(nip_add.getText()) != 0) {
            output_kontrachent.setText("\tSzukam po nipie\n");
            output_kontrachent.setText(szukaj_kontrachenta.get_kontrachent(Integer.parseInt(nip_add.getText())));
        } else {
            output_kontrachent.setText("Błąd szukania. Dozwolone wyszukiwanie wg nazwy klienta lub numeru ID klienta");
        }
    }//GEN-LAST:event_SzukajActionPerformed

    private void kontrachent_dodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kontrachent_dodajActionPerformed
        /**
         * dodawanie kontrachenta
         */
        Kontrachent nowy_kontrachent = new Kontrachent();
        String nazwa = nazwa_add.getText();
        String ulica = ulica_add.getText();
        String miasto = miasto_add.getText();
        String kod = kod_add.getText();
        int nr_dom = Integer.parseInt(dom_add.getText());
        int nr_lok = Integer.parseInt(lokal_add.getText());
        long nip = Long.parseLong(nip_add.getText());
        int regon = Integer.parseInt(regon_add.getText());
        output_kontrachent.setText(nowy_kontrachent.dodaj_kontrachent(nip, regon, nazwa, ulica, miasto, kod, nr_dom, nr_lok));
        //String adres = miasto + ' ' + ulica + ' ' + kod + ' ' + nr_dom + ' ' + nr_lok;
        //String out = "nazwa +'\n'+ulica+'\n'+miasto+'\n'+kod+'\n'+nr_dom+'\n'+nr_lok+'\n'+nip+'\n'+regon";
        //output_kontrachent.setText(out);
    }//GEN-LAST:event_kontrachent_dodajActionPerformed

    private void art_szukajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_art_szukajActionPerformed
        /**
         * szukanie artykulu
         */
        Artykul nowy_item = new Artykul();
        if (art_nazwa.getText().length() != 0) {
            art_output.setText(nowy_item.get_art(art_nazwa.getText()));
        } else {
            art_output.setText(nowy_item.get_art_ean(Integer.parseInt(art_ean.getText())));
        }

    }//GEN-LAST:event_art_szukajActionPerformed

    private void art_dodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_art_dodajActionPerformed
        /**
         * dodawanie artykulu
         */
        Artykul nowy_item = new Artykul();
        String nazwa = art_nazwa.getText();
        String jednostka = art_jm.getText();
        int ean = Integer.parseInt(art_ean.getText());
        int ilosc = Integer.parseInt(art_ilosc.getText());
        int polka = Integer.parseInt(art_polka.getText());
        int regal = Integer.parseInt(art_regal.getText());
        nowy_item.dodaj_nowy_artykul(ilosc, ean, polka, regal, nazwa, jednostka);
        String nagl = "Dodano artykuł: \n";
        String out = "Nazwa: " + nazwa + '\n' + "Jednostka miary: " + jednostka + '\n' + "EAN: " + ean + '\n' + "Ilość: " + ilosc + '\n' + "Półka: " + polka + '\n' + "Regał: " + regal;
        art_output.setText(out);
    }//GEN-LAST:event_art_dodajActionPerformed

    private void zamowienie_szukajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamowienie_szukajActionPerformed
        /**
         * wyszukiwanie zamowienia
         */
        Zamowienie zam = new Zamowienie();
        if (zamowienie_dla.getText().length() != 0)
        {
            zamowienie_output.setText(zam.szukaj_zamowienia_nip(Integer.parseInt(zamowienie_dla.getText())));
        }
        else if (zamowienie_nr_dok.getText().length() != 0)
        {
            zamowienie_output.setText(zam.szukaj_zamowienia(Integer.parseInt(zamowienie_nr_dok.getText())));
        }
        else if (zamowienie_data.getText().length() != 0)
        {
            zamowienie_output.setText(zam.szukaj_zamowienia(zamowienie_data.getText()));
        }
        else
            zamowienie_output.setText("Błąd szukania. Dozwolone wyszukiwanie wg numeru  ID klienta, nr dokumentu lub daty w formacie rrrr-mm-dd");

    }//GEN-LAST:event_zamowienie_szukajActionPerformed

    private void create_bazeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_bazeActionPerformed
        /**
         * opcja w menu tworzenia bazy i tabel
         */
        create_db cdb = new create_db();
        cdb.setVisible(true);
    }//GEN-LAST:event_create_bazeActionPerformed

    private void dodaj_sztukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodaj_sztukActionPerformed
        /**
         * dodawanie sztuk wybranego artykulu
         */
        Artykul item = new Artykul();
        int sztuk = Integer.parseInt(art_ilosc1.getText());
        int ean = Integer.parseInt(art_ean1.getText());
        String out = item.dodaj_sztuk(sztuk, ean);
        art_output.setText(out);

    }//GEN-LAST:event_dodaj_sztukActionPerformed

    private void usun_sztuk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usun_sztuk1ActionPerformed
        /**
         * usuwanie sztuk wybranego artykulu
         */
        Artykul item = new Artykul();
        int sztuk = Integer.parseInt(art_ilosc1.getText());
        int ean = Integer.parseInt(art_ean1.getText());
        String out = item.usun_sztuk(sztuk, ean);
        art_output.setText(out);
    }//GEN-LAST:event_usun_sztuk1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // pokazuje info
        Show_Info info  = new Show_Info();
        info.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Mag().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Szukaj;
    private javax.swing.JButton art_dodaj;
    private javax.swing.JTextField art_ean;
    private javax.swing.JTextField art_ean1;
    private javax.swing.JTextField art_ilosc;
    private javax.swing.JTextField art_ilosc1;
    private javax.swing.JTextField art_jm;
    private javax.swing.JTextField art_nazwa;
    private javax.swing.JTextPane art_output;
    private javax.swing.JTextField art_polka;
    private javax.swing.JTextField art_regal;
    private javax.swing.JButton art_szukaj;
    private javax.swing.JMenuItem check_pol;
    private javax.swing.JMenuItem create_baze;
    private javax.swing.JButton dodaj_sztuk;
    private javax.swing.JTextField dom_add;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField kod_add;
    private javax.swing.JButton kontrachent_dodaj;
    private javax.swing.JTextField lokal_add;
    private javax.swing.JTextField miasto_add;
    private javax.swing.JTextField nazwa_add;
    private javax.swing.JTextField nip_add;
    private javax.swing.JTextField nr_dok_pz;
    private javax.swing.JTextField nr_dok_wz;
    private javax.swing.JTextPane output_kontrachent;
    private javax.swing.JButton pz_dodaj;
    private javax.swing.JTextField pz_ilosc;
    private javax.swing.JTextField pz_item;
    private javax.swing.JTextField pz_num;
    private javax.swing.JTextField pz_od;
    private javax.swing.JTextPane pz_output;
    private javax.swing.JButton pz_szukaj_button;
    private javax.swing.JTextField regon_add;
    private javax.swing.JMenu show_info;
    private javax.swing.JMenu sprawdz_pol;
    private javax.swing.JTextField szukaj_wz;
    private javax.swing.JTextField ulica_add;
    private javax.swing.JButton usun_sztuk1;
    private javax.swing.JButton wz_add_button;
    private javax.swing.JTextField wz_dokogo;
    private javax.swing.JButton wz_find;
    private javax.swing.JTextField wz_ile;
    private javax.swing.JTextField wz_item;
    private javax.swing.JTextPane wz_output;
    private javax.swing.JButton zamowienie_add;
    private javax.swing.JTextField zamowienie_data;
    private javax.swing.JTextField zamowienie_dla;
    private javax.swing.JTextField zamowienie_ilosc;
    private javax.swing.JTextField zamowienie_item;
    private javax.swing.JTextField zamowienie_nr_dok;
    private javax.swing.JTextPane zamowienie_output;
    private javax.swing.JButton zamowienie_szukaj;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
